force-app/main/default/objects/Case/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Review Decision</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Decision_Code__c.field-meta.xml
<CustomField>
    <fullName>Decision_Code__c</fullName>
    <label>Decision Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uphold</fullName>
            </value>
            <value>
                <fullName>Overturn</fullName>
            </value>
            <value>
                <fullName>Partial Overturn</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
                <isActive>false</isActive>
                <label>Dismissed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Account.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Priority__c.field-meta.xml
<CustomField>
    <fullName>Program_Priority__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Priority</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Priority__c.Program_Review_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_Review_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Priority__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Received_Date__c</fullName>
    <label>Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Review_Fee__c.field-meta.xml
<CustomField>
    <fullName>Review_Fee__c</fullName>
    <label>Review Fee</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Health Plan</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>CURA/URA</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>ACO/RBPO</fullName>
            </value>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
                <isActive>false</isActive>
                <label>Law Firm</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Provider Representative</fullName>
                <isActive>false</isActive>
                <label>Provider Representative</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/Entity_Address__c.object-meta.xml
<CustomObject>
    <label>Entity Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Contact</label>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/Entity_Contact__c.object-meta.xml
<CustomObject>
    <label>Entity Contact</label>
    <nameField>
        <label>Contact Person First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Contact__c/fields/Created_By_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>Created_By_MDIRO__c</fullName>
    <label>Created By</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/Invoice_Details__c.object-meta.xml
<CustomObject>
    <label>Invoice Detail</label>
    <nameField>
        <label>Invoice Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Details__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Case_IR_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_IR_Number__c</fullName>
    <formula>Case__r.Case_Number_f__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case IR Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <formula>TEXT(Case__r.Decision_Code__c)</formula>
    <label>Decision</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Contact</label>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Review_Fee__c.field-meta.xml
<CustomField>
    <fullName>Review_Fee__c</fullName>
    <label>Review Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Program_Priority__c/Program_Priority__c.object-meta.xml
<CustomObject>
    <label>Child Reference Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Priority__c/fields/Decision_Code__c.field-meta.xml
<CustomField>
    <fullName>Decision_Code__c</fullName>
    <label>Decision Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Overturn</fullName>
            </value>
            <value>
                <fullName>Partial Overturn</fullName>
            </value>
            <value>
                <fullName>Uphold</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseUtilityBatch.cls
public class CaseUtilityBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            'select Id,Case__c,Case_IR_Number__c,Decision__c,Entity__r.Entity_Type__c,Program_Code__c,Review_Fee__c, '+
            'Project_Id__c,Entity__c,Entity_Contact__c,Entity_Contact__r.Entity_Address__r.Entity__c '+
            'from Invoice_Details__c '+
            'Where Case__r.Status = \'Completed\' AND Case__r.Invoiced__c = false'
            /*'SELECT ID, Status, Created_By_MDIRO__c, Program_Code__c, Program_Priority__c, Decision_Code__c, Received_Date__c ' +
            'FROM Case ' +
            'Where Status = \'Completed\' AND Invoiced__c = false'*/
        );
    }
    
    public void execute(Database.BatchableContext bc, List<Invoice_Details__c> records){
        // process each batch of records
        CaseTriggerHelper.createInvoiceHeaderRecord(records);
    }
    
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}