force-app/main/default/objects/Account/fields/Case_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Case_Sequence__c</fullName>
    <label>Case Sequence</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Party__c.field-meta.xml
<CustomField>
    <fullName>Contract_Party__c</fullName>
    <label>Contract Party</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_State__c.field-meta.xml
<CustomField>
    <fullName>Project_State__c</fullName>
    <label>Project State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Case_Sequence__c</fullName>
    <label>Case Sequence</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Created_Date_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>Created_Date_MDIRO__c</fullName>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Account.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Priority__c.field-meta.xml
<CustomField>
    <fullName>Program_Priority__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Priority</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Program_Priority__c.Program_Review_Type__c</field>
            <operation>equals</operation>
            <valueField>$Source.Program_Review_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Program_Priority__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Review_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Review Type</label>
    <referenceTo>Program_Review_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Updated_Date_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>Updated_Date_MDIRO__c</fullName>
    <label>Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Health Plan</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>CURA/URA</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>ACO/RBPO</fullName>
            </value>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
                <isActive>false</isActive>
                <label>Law Firm</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Provider Representative</fullName>
                <isActive>false</isActive>
                <label>Provider Representative</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/Entity_Address__c.object-meta.xml
<CustomObject>
    <label>Entity Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Contact</label>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/Entity_Contact__c.object-meta.xml
<CustomObject>
    <label>Entity Contact</label>
    <nameField>
        <label>Contact Person First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Contact__c/fields/Contact_Person_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_First_Name__c</fullName>
    <label>Contact Person First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Contact_Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Last_Name__c</fullName>
    <label>Contact Person Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participants Enrollee</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants - Enrollee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Individual</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipName>Participants_Enrollee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Provider Representative</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Health Plan</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/isDeleted_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>isDeleted_MDIRO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDeleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Participant_Enrollee_Type__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollee_Type__c</fullName>
    <label>Individual Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requestor</fullName>
            </value>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
                <isActive>false</isActive>
                <label>Law Firm</label>
            </value>
            <value>
                <fullName>Member</fullName>
                <isActive>false</isActive>
                <label>Member</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Representative</fullName>
                <isActive>false</isActive>
                <label>Representative</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Priority__c/Program_Priority__c.object-meta.xml
<CustomObject>
    <label>Child Reference Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Priority__c/fields/Program_Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Review_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Review Type</label>
    <referenceTo>Program_Review_Type__c</referenceTo>
    <relationshipName>Program_Priorities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Priority__c/recordTypes/Priority_Type.recordType-meta.xml
<RecordType>
    <fullName>Priority_Type</fullName>
    <active>true</active>
    <label>Priority Type</label>
</RecordType>

force-app/main/default/objects/Program_Review_Type__c/Program_Review_Type__c.object-meta.xml
<CustomObject>
    <label>Reference Data</label>
    <nameField>
        <label>Review Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Review_Type__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Program_Name__r.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Review_Type__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Review_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Review_Type__c/recordTypes/Review_Type.recordType-meta.xml
<RecordType>
    <fullName>Review_Type</fullName>
    <active>true</active>
    <label>Review Type</label>
</RecordType>

force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FD</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>VA</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/createCaseAPIsTest.cls
@isTest
public class createCaseAPIsTest {
    
    @testSetup static void testData(){
        //Insert Account
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Program_Code__c = 'test';
        acc.Case_Sequence__c = '5';
        acc.Contract_Party__c = 'Maryland Department of Health';
        acc.Project_State__c = 'MD';
        Insert acc;
        
        Id prgRevRecordTypeId =  Schema.SObjectType.Program_Review_Type__c.getRecordTypeInfosByDeveloperName().get('Review_Type').getRecordTypeId();
        Id prgPriRecordTypeId =  Schema.SObjectType.Program_Priority__c.getRecordTypeInfosByDeveloperName().get('Priority_Type').getRecordTypeId();
        //Insert Program_Review_Type__c
        Program_Review_Type__c pReview = new Program_Review_Type__c();
        pReview.Name = 'Coverage';
        pReview.Program_Name__c = acc.Id;
        pReview.RecordTypeId = prgRevRecordTypeId;
        Insert pReview;
        
        //Insert Program_Priority__c
        Program_Priority__c prgPriority = new Program_Priority__c();
        prgPriority.Name = 'Standard';
        prgPriority.recordTypeId = prgPriRecordTypeId;
        prgPriority.Program_Review_Type__c = pReview.Id;
        Insert prgPriority;
        Program_Priority__c prgPriority1 = new Program_Priority__c();
        prgPriority1.Name = 'Expedited';
        prgPriority1.recordTypeId = prgPriRecordTypeId;
        prgPriority1.Program_Review_Type__c = pReview.Id;
        Insert prgPriority1;
        //case
        Case c = new Case();
        c.Status ='New';
        c.Origin ='Web';
        c.AccountId = acc.Id;
        c.Created_Date_MDIRO__c = System.today();
        c.Updated_Date_MDIRO__c = System.today();
        Insert c;
        //Participant__c
        Participant__c participant = new Participant__c();
        participant.Case__c = c.Id;
        participant.Participant_Enrollee_Type__c = 'Requestor';
        Insert participant;
        
        Entity__c entity1 = new Entity__c();
        //entity1.isDeleted_MDIRO__c  = false;
        entity1.Name = 'Test Entity';
        entity1.Project_id__c = 'Test';
        entity1.Entity_Type__c = 'MCO';
        Insert entity1;
        
        //Insert Entity_Address__c
        Entity_Address__c address = new Entity_Address__c();
        address.Entity__c = entity1.Id;
        address.Address_1__c = 'test drive';
        address.State__c = 'VA';
        address.City__c = 'test';
        address.Zip__c = '20190';
        Insert address;
        
        //Insert Entity_Contact__c
        Entity_Contact__c entityContact1 = new Entity_Contact__c();
        //entityContact1.Name = 'Test';
        entityContact1.Contact_Person_Last_Name__c = 'user';
        entityContact1.Contact_Person_First_Name__c = 'test';
        entityContact1.Entity_Address__c = address.Id;
        Insert entityContact1;
        
        
    }
    //Method 1 : Request URL last index = 'persistMDIROCase' and without programCode, reviewTypeCd and, priorityTypeCd
    @isTest static void testMethod1(){
        Test.startTest();
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "rCaseDispute" : {}, "rFiles": [], "rCaseParticipants":[]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        /*SF_MD_GCaseDetails wrapperObj =*/ //createCaseAPIs.saveCase();
        //System.assertEquals(417, wrapperObj.statusCode);
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //entityTypeCode = 'PRP'
    @isTest static void testMethod2(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : "'+c.Id+'", "rCaseDispute" : {}, "rFiles": [], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "PRP"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        Test.stopTest();
    }
    
        @isTest static void testMethod0(){
        Test.startTest();
        Case c = [SELECT Id,Program_Priority__c FROM Case LIMIT 1];
        Program_Priority__c pp=[select id,Program_Review_Type__c from Program_Priority__c where name='Expedited' limit 1];
            Program_Review_Type__c pr=[select id from Program_Review_Type__c where id=: pp.Program_Review_Type__c limit 1];
            c.Program_Priority__c=pp.id;
            c.Program_Review_Type__c=pr.id;
            update c;
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //entityTypeCode = 'PRP'
    //With Entity Id
    @isTest static void testMethod3(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        Entity__c en = [SELECT Id FROM Entity__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : "'+c.Id+'", "rCaseDispute" : {}, "rFiles": [], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "PRP", "entityId": "'+en.Id+'", "firstName":"Test"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //entityTypeCode = 'MCO'
    //With Entity Id
    @isTest static void testMethod4(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        Entity__c en = [SELECT Id FROM Entity__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : "'+c.Id+'", "rCaseDispute" : {}, "rFiles": [], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "MCO", "entityId": "'+en.Id+'", "firstName":"Test"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //entityTypeCode = null/'PRV'
    //With Entity Id
    @isTest static void testMethod5(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        Entity__c en = [SELECT Id FROM Entity__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : "'+c.Id+'", "rCaseDispute" : {}, "rFiles": [], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "PRV", "entityId": "'+en.Id+'", "firstName":"Test"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //entityTypeCode = null/'PRV'
    //Without Entity Id
    //With File data
    @isTest static void testMethod6(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : "'+c.Id+'", "rCaseDispute" : {}, "rFiles": [{"filePath":"test"}], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "PRV", "entityId": null, "firstName":"Test"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //Wirhout Case Id
    //entityTypeCode = null/'PRV'
    //With Entity Id
    //With File data
    @isTest static void testMethod7(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        Entity__c en = [SELECT Id FROM Entity__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : null, "rCaseDispute" : {}, "rFiles": [{"filePath":"test"}], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "PRV", "entityId": "'+en.id+'", "firstName":"Test"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //Wirhout Case Id
    //entityTypeCode = 'MCO'
    //With Entity Id
    //With File data
    @isTest static void testMethod8(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        Entity__c en = [SELECT Id FROM Entity__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : null, "rCaseDispute" : {}, "rFiles": [{"filePath":"test"}], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'"}},{"rEntityParticipant":{ "entityTypeCode": "MCO", "entityId": "'+en.id+'", "firstName":"Test","entityFullName":"Test Entity"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    //Request URL last index 'persistMDIROCase' and with programCode, reviewTypeCd and, priorityTypeCd
    //Wirhout Case Id
    //entityTypeCode = 'MCO'
    //With Entity Id
    //With File data
    @isTest static void testMethod9(){
        Test.startTest();
        Case c = [SELECT Id FROM Case LIMIT 1];
        Participant__c participant = [SELECT Id FROM Participant__c LIMIT 1];
        Entity__c en = [SELECT Id FROM Entity__c LIMIT 1];
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'https://maximushealthcareappeals--maxdev.my.salesforce.com/services/apexrest/api/appealCaseRemoteService/persistMDIROCase';
        request.httpMethod = 'POST';
        RestContext.request = request;
        request.requestBody = Blob.valueof('{ "programCode": "test", "reviewTypeCd" : "test", "priorityTypeCd": "test", "id" : null, "rCaseDispute" : {}, "rFiles": [{"filePath":"test"}], "rCaseParticipants":[ {"rPersonParticipant" :{ "personId": "'+participant.Id+'","firstNameTxt":" TestFirstName", "lastNameTxt":"LastName", "insuranceId":"Test","personTypeCd":"ENRO"}},{"rEntityParticipant":{ "entityTypeCode": "MCO", "entityId": "'+en.id+'", "firstName":"Test","entityFullName":"Test"}}]}');
        response.addHeader('Content-Type', 'application/json');
        RestContext.response = response;
        //createCaseAPIs.saveCase();
        
        Test.stopTest();
    }
    
    @isTest static void testMethod10(){
        Test.startTest();
        SF_MD_DefaultResponseWrapper tst=new SF_MD_DefaultResponseWrapper();
        tst.statusCode=200;
        tst.message='test';
        Test.stopTest();
        
    }
    
      @isTest
    static void testSF_MD_CasesWithParticipants() {
        // Create an instance of the main class
        SF_MD_CasesWithPartcipants caseWithParticipants = new SF_MD_CasesWithPartcipants();
        
        // Set some fields to ensure coverage
        caseWithParticipants.id = '001xx000003DGbPAAW';
        caseWithParticipants.caseNumber = 'C-12345';
        caseWithParticipants.pendingRi = true;
        caseWithParticipants.sfCaseNumber = 'SF123';
        caseWithParticipants.deletedFlag = false;
        caseWithParticipants.reviewTypeCd = 'RT001';
        caseWithParticipants.priorityTypeCd = 'High';
        caseWithParticipants.priorityTypeDesc = 'High Priority';
        caseWithParticipants.referenceNumber = 'REF-001';
        caseWithParticipants.recievedDateStr = '2023-01-01';
        caseWithParticipants.recievedDate = DateTime.now();
        caseWithParticipants.startDateStr = '2023-01-05';
        caseWithParticipants.startDate = DateTime.now().addDays(5);
        caseWithParticipants.createUser = 'TestUser1';
        caseWithParticipants.updatedUser = 'TestUser2';
        caseWithParticipants.daysLeft = 10;
        caseWithParticipants.createTimestamp = DateTime.now().getTime();
        caseWithParticipants.updateTimestamp = DateTime.now().getTime();
        caseWithParticipants.reason = 'Test Reason';
        caseWithParticipants.statusCd = 'Active';
        caseWithParticipants.statusCdForWeb = 'Active';
        caseWithParticipants.dateOfDecision = DateTime.now().addDays(7);
        caseWithParticipants.dateLetterSent = Date.today().addDays(7);
        caseWithParticipants.decisionCodeDescription = 'Approved';
        caseWithParticipants.sourceType = 'External';
        caseWithParticipants.programId = 'PRG001';
        caseWithParticipants.programCode = 'P001';
        caseWithParticipants.providerRepName = 'Provider Rep';
        caseWithParticipants.providerName = 'Provider Name';
        caseWithParticipants.patientName = 'John Doe';
        
        // Test caseParticipants inner class
        SF_MD_CasesWithPartcipants.caseParticipants caseParticipant = new SF_MD_CasesWithPartcipants.caseParticipants();
        caseParticipant.id = 'P001';
        
        // Set RpersonParticipant for caseParticipant
        SF_MD_CasesWithPartcipants.RpersonParticipant personParticipant = new SF_MD_CasesWithPartcipants.RpersonParticipant();
        personParticipant.personId = 'PP001';
        personParticipant.firstNameTxt = 'John';
        personParticipant.lastNameTxt = 'Doe';
        personParticipant.emailAddress = 'john.doe@example.com';
        personParticipant.phoneNumber = '1234567890';
        caseParticipant.rPersonParticipant = personParticipant;

        // Set RentityParticipant for caseParticipant
        SF_MD_CasesWithPartcipants.RentityParticipant entityParticipant = new SF_MD_CasesWithPartcipants.RentityParticipant();
        entityParticipant.entityId = 'E001';
        entityParticipant.entityFullName = 'Test Entity';
        entityParticipant.phoneNumber = '9876543210';
        caseParticipant.rEntityParticipant = entityParticipant;
        
        // Add caseParticipants to the main class
        caseWithParticipants.rCaseParticipants.add(caseParticipant);
        
        // Test files inner class
        SF_MD_CasesWithPartcipants.files file = new SF_MD_CasesWithPartcipants.files();
        file.name = 'Test File';
        file.uploadBy = 'TestUser1';
        file.documentType = 'PDF';
        file.uploadTime = DateTime.now();
        file.length = 12345L;
        file.docRecId = 'DOC001';
        caseWithParticipants.rFiles.add(file);

        // Test caseDispute inner class
        SF_MD_CasesWithPartcipants.caseDispute caseDispute = new SF_MD_CasesWithPartcipants.caseDispute();
        caseDispute.dateInitialClaimDenial = Date.today();
        caseDispute.diagnosisTypeDescription = 'Diagnosis Test';
        caseWithParticipants.rCaseDispute = caseDispute;

        // Insert necessary records if required (depending on your org setup)
        // For example, if Case object or related data needs to be inserted

        // Test assertions to ensure data integrity
        System.assertEquals('001xx000003DGbPAAW', caseWithParticipants.id);
        System.assertEquals('John', caseWithParticipants.rCaseParticipants[0].rPersonParticipant.firstNameTxt);
        System.assertEquals('Test File', caseWithParticipants.rFiles[0].name);
        System.assertEquals('Diagnosis Test', caseWithParticipants.rCaseDispute.diagnosisTypeDescription);
    }
}