force-app/main/default/objects/Account/fields/Contract_Party__c.field-meta.xml
<CustomField>
    <fullName>Contract_Party__c</fullName>
    <label>Contract Party</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_State__c.field-meta.xml
<CustomField>
    <fullName>Project_State__c</fullName>
    <label>Project State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Decision_Code__c.field-meta.xml
<CustomField>
    <fullName>Decision_Code__c</fullName>
    <label>Decision Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uphold</fullName>
            </value>
            <value>
                <fullName>Overturn</fullName>
            </value>
            <value>
                <fullName>Partial Overturn</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
                <isActive>false</isActive>
                <label>Dismissed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Decision_Date_Closing__c.field-meta.xml
<CustomField>
    <fullName>Decision_Date_Closing__c</fullName>
    <label>Decision Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Letter_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Letter_Sent_Date__c</fullName>
    <label>Letter Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Account.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/CaseEntityJunction__c.object-meta.xml
<CustomObject>
    <label>Participant Entity</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Entity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseEntityJunction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entity</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Participant Entities</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity_Address__c.Entity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Entity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entity Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity_Contact__c.Entity_Address__c</field>
            <operation>equals</operation>
            <valueField>$Source.Entity_Address__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Participant Entities</relationshipLabel>
    <relationshipName>Entiy_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <formula>TEXT(Entity__r.Entity_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Health Plan</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>CURA/URA</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>ACO/RBPO</fullName>
            </value>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
                <isActive>false</isActive>
                <label>Law Firm</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Provider Representative</fullName>
                <isActive>false</isActive>
                <label>Provider Representative</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Secondary_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Name__c</fullName>
    <label>Secondary Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/TAX_ID__c.field-meta.xml
<CustomField>
    <fullName>TAX_ID__c</fullName>
    <label>TAX ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/Entity_Address__c.object-meta.xml
<CustomObject>
    <label>Entity Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Address__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Office Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entity_Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Contact</label>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/Entity_Contact__c.object-meta.xml
<CustomObject>
    <label>Entity Contact</label>
    <nameField>
        <label>Contact Person First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Contact__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/Invoice_Details__c.object-meta.xml
<CustomObject>
    <label>Invoice Detail</label>
    <nameField>
        <label>Invoice Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Details__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Details__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Contact</label>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/Invoice_Header__c.object-meta.xml
<CustomObject>
    <label>Invoice Header</label>
    <nameField>
        <displayFormat>IH-{0000}</displayFormat>
        <label>Invoice Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Header__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Invoice Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipLabel>Invoice Headers</relationshipLabel>
    <relationshipName>Invoice_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Entity_type__c.field-meta.xml
<CustomField>
    <fullName>Entity_type__c</fullName>
    <formula>Text(Entity__r.Entity_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Header__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FD</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>VA</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseUtilityBatchTest.cls
@isTest
public class CaseUtilityBatchTest {
    
    
@testSetup
    public static void dataSetup(){
        Account acc = new Account();
        acc.Name ='Test';
        acc.BillingCity = 'Test City';
        acc.BillingCountry  = 'Test Country';
        acc.Project_State__c='MN';
        acc.Program_Code__c='MN';
        acc.Contract_Party__c='State of Minnesota';
        insert acc;

        // setup required records
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Test Last';
        con.AccountId = acc.Id;
        insert con;


        Case cs = new Case();
        cs.AccountId = acc.Id;
        cs.ContactId = con.Id;
        cs.Status = 'Completed';
        cs.Decision_Date_Closing__c= system.today();
        cs.Decision_Code__c = 'Uphold';
        cs.Letter_Sent_Date__c = System.today().toStartOfMonth().addDays(-2);
        insert cs;
        
		/*
        List<MAXAttachments__c> attlist = new List<MAXAttachments__c>();
        
        MAXAttachments__c mx = new MAXAttachments__c();
        mx.Case__c = cs.Id;
        mx.Document_Type__c='PowerofAttorneyAgreement';
        mx.Document_Status__c='Processing';
        attlist.add(mx);
        
        
        MAXAttachments__c mx1 = new MAXAttachments__c();
        mx1.Case__c = cs.Id;
        mx1.Document_Type__c='Additional Member Info';
        mx1.Document_Status__c='Processing';
        mx1.Share_To_Expert__c = true;
        attlist.add(mx1);
        insert attlist;
        */
        List<Entity__c> entities = new List<Entity__c>();
        Entity__c en = new Entity__c();
        en.Name = 'Test';
        en.Secondary_Name__c = 'entity';
        en.TAX_ID__c= '1234';
        en.Entity_Type__c = 'Representative';
        en.Project_Id__c = 'IR';
        entities.add(en);
        
        Entity__c en2 = new Entity__c();
        en2.Name = 'Test2';
        en2.Secondary_Name__c = 'entity';
        en2.TAX_ID__c= '1234';
        en2.Entity_Type__c = 'Provider';
        en2.Project_Id__c = 'IR';
        entities.add(en2);
        
        Entity__c en3 = new Entity__c();
        en3.Name = 'Test';
        en3.Secondary_Name__c = 'entity';
        en3.TAX_ID__c= '1234';
        en3.Project_Id__c = 'IR';
        en3.Entity_Type__c = 'MCO';
        entities.add(en3);
        
        insert entities;
        
        List<Entity_Address__c> addresses = new List<Entity_Address__c>();
        Entity_Address__c enAdd = new Entity_Address__c();
        enAdd.Name = 'test dr.,';
        enAdd.Address_1__c = 'ste 200';
        enAdd.Address_2__c = 'ste 400';
        enAdd.City__c = 'Reston';
        enAdd.State__c = 'VA';
        enAdd.Zip__c = '20190';
        enAdd.Entity__c = en.Id;
        enAdd.Address_Type__c='Billing Address';
        addresses.add(enAdd);
        
        Entity_Address__c enAdd2 = new Entity_Address__c();
        enAdd2.Name = 'test dr.,';
        enAdd2.Address_1__c = 'ste 200';
        enAdd2.Address_2__c = 'ste 400';
        enAdd2.City__c = 'Reston';
        enAdd2.State__c = 'VA';
        enAdd2.Zip__c = '20191';
        enAdd2.Entity__c = en2.Id;
        enAdd2.Address_Type__c='Billing Address';
        addresses.add(enAdd2);
        
        Entity_Address__c enAdd3 = new Entity_Address__c();
        enAdd3.Name = 'test dr.,';
        enAdd3.Address_1__c = 'ste 200';
        enAdd3.Address_2__c = 'ste 400';
        enAdd3.City__c = 'Reston';
        enAdd3.State__c = 'VA';
        enAdd3.Zip__c = '20192';
        enAdd3.Entity__c = en3.Id;
        enAdd3.Address_Type__c='Billing Address';
        addresses.add(enAdd3);
        
        insert addresses;
        
        List<Entity_Contact__c> enContacts = new List<Entity_Contact__c>();
        Entity_Contact__c enCon = new Entity_Contact__c();
        enCon.name = 'test';
        enCon.Contact_Person_First_Name__c='test';
        enCon.Contact_Person_Last_Name__c = 'user';
        enCon.Entity__c= en.Id;
        enCon.Email_Address__c = 'a.a@g.co';
        enCon.Entity_Address__c= enAdd.Id;
        enCon.Email_Address__c = cs.Created_By_MDIRO__c;
        enContacts.add(enCon);
        
        Entity_Contact__c enCon2 = new Entity_Contact__c();
        enCon2.name = 'test';
        enCon2.Contact_Person_First_Name__c='test';
        enCon2.Contact_Person_Last_Name__c = 'user';
        enCon2.Entity__c= en2.Id;
        enCon2.Email_Address__c = 'a.a@g.co';
        enCon2.Entity_Address__c= enAdd2.Id;
        enCon2.Email_Address__c = cs.Created_By_MDIRO__c;
        enContacts.add(enCon2);
        
        Entity_Contact__c enCon3 = new Entity_Contact__c();
        enCon3.name = 'test';
        enCon3.Email_Address__c = 'a.a@g.co';
        enCon3.Contact_Person_First_Name__c='test';
        enCon3.Contact_Person_Last_Name__c = 'user';
        enCon3.Entity__c= en3.Id;
        enCon3.Entity_Address__c= enAdd3.Id;
        enCon3.Email_Address__c = cs.Created_By_MDIRO__c;
        enContacts.add(enCon3);
        
        insert enContacts;
        
        List<CaseEntityJunction__c> cejs = new List<CaseEntityJunction__c>();
        CaseEntityJunction__c ce = new CaseEntityJunction__c();
        ce.Is_Send_Billing_To__c = false;
        ce.Case__c = cs.Id;
        ce.Entity__c = en.Id;
        ce.Entity_Address__c = enAdd.Id;
        ce.Entity_Contact__c = enCon.Id;
        ce.Addressee__c = false;
        cejs.add(ce);
        
        CaseEntityJunction__c ce2 = new CaseEntityJunction__c();
        ce2.Is_Send_Billing_To__c = false;
        ce2.Case__c = cs.Id;
        ce2.Entity__c = en2.Id;
        ce2.Entity_Address__c = enAdd2.Id;
        ce2.Entity_Contact__c = enCon2.Id;
        ce2.Addressee__c = false;
        cejs.add(ce2);
        
        CaseEntityJunction__c ce3 = new CaseEntityJunction__c();
        ce3.Is_Send_Billing_To__c = false;
        ce3.Case__c = cs.Id;
        ce3.Entity__c = en3.Id;
        ce3.Entity_Address__c = enAdd3.Id;
        ce3.Entity_Contact__c = enCon3.Id;
        ce3.Addressee__c = false;
        cejs.add(ce3);
        
        CaseEntityJunction__c ce4 = new CaseEntityJunction__c();
        ce4.Is_Send_Billing_To__c = false;
        ce4.Case__c = cs.Id;
        ce4.Entity__c = en2.Id;
        ce4.Entity_Address__c = enAdd2.Id;
        ce4.Entity_Contact__c = enCon2.Id;
        ce4.Addressee__c = false;
        cejs.add(ce4);
        
		CaseEntityJunction__c ce5 = new CaseEntityJunction__c();
        ce5.Is_Send_Billing_To__c = false;
        ce5.Case__c = cs.Id;
        ce5.Entity__c = en3.Id;
        ce5.Entity_Address__c = enAdd3.Id;
        ce5.Entity_Contact__c = enCon3.Id;
        ce5.Addressee__c = false;
        cejs.add(ce5);
		
        insert cejs;
        
        Invoice_Header__c invoice = new Invoice_Header__c();
        //invoice.Entity_Contact__c = entityContact.Id;
        invoice.Entity__c = en.Id;
        invoice.Status__c = 'Unpaid';
        invoice.Invoice_Date__c = Date.Today();
        //invoice.Invoice_Number__c = '123invoicetest';
        Insert invoice;
        
        Invoice_Details__c detailObj = new Invoice_Details__c();
        detailObj.Invoice_Header__c = invoice.Id;
        detailObj.Case__c = cs.Id;
        detailObj.Program_Code__c = 'IR';
        insert detailObj;
        //Invoice_Number__c obj = new Invoice_Number__c(Sequence__c=1);
        //INSERT obj;
    }
    
    @isTest static void testMethods() {
        Test.startTest();
        CaseUtilityScheduler ob = new CaseUtilityScheduler();
       
        ob.execute(null);
       
        Test.stopTest();
    }
}