force-app/main/default/objects/Account/fields/Enable_Document_List__c.field-meta.xml
<CustomField>
    <fullName>Enable_Document_List__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Document List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Link_To_Document_List_Sample__c.field-meta.xml
<CustomField>
    <fullName>Link_To_Document_List_Sample__c</fullName>
    <inlineHelpText>Enter the URL where the document list sample is stored</inlineHelpText>
    <label>Link To Document List Sample</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Board__mdt/Board__mdt.object-meta.xml
<CustomObject>
    <label>Board</label>
    <pluralLabel>Boards</pluralLabel>
</CustomObject>

force-app/main/default/objects/Board__mdt/fields/Board_Value__c.field-meta.xml
<CustomField>
    <fullName>Board_Value__c</fullName>
    <label>Board Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Account.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_Specialty__c.field-meta.xml
<CustomField>
    <fullName>Requested_Specialty__c</fullName>
    <label>Requested Specialty</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CasedisputeController.cls
public class CasedisputeController {

    
     @AuraEnabled
    public static Case getCase(String caseId){
       
        system.debug('caseId'+caseId);
        Case ca = [Select id, Account.Program_Code__c,Account.Link_To_Document_List_Sample__c ,Account.Enable_Document_List__c,Requested_Specialty__c from Case where id =: caseId];
        
        return ca;
    }

    @AuraEnabled(cacheable = true)
    public static List<Board__mdt> getRequestedSpecialty(){
        return [SELECT Id,Board_Value__c FROM Board__mdt WHERE Status__c = 'Active' ORDER BY Board_Value__c ];
    }
    
}