force-app/main/default/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Send_Billing_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Billing_To__c</fullName>
    <label>Send Billing To</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Enrollee</fullName>
            </value>
            <value>
                <fullName>Health Plan</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Provider</fullName>
            </value>
            <value>
                <fullName>Provider Representative</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Addressee__c.field-meta.xml
<CustomField>
    <fullName>Addressee__c</fullName>
    <label>Addressee</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Document_Address__c.field-meta.xml
<CustomField>
    <fullName>Document_Address__c</fullName>
    <label>Document Address</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Document_Addressee__c.field-meta.xml
<CustomField>
    <fullName>Document_Addressee__c</fullName>
    <label>Document Addressee</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Account.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Send_Billing_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Billing_To__c</fullName>
    <formula>IF(INCLUDES( Account.Send_Billing_To__c , &quot;Client; &quot;), &quot;Client&quot;, NULL)  &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Enrollee; &quot;), &quot;Enrollee&quot;, NULL)  &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Health Plan; &quot;), &quot;Health Plan&quot;, NULL) &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Law Firm; &quot;), &quot;Law Firm&quot;, NULL) &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;MCO; &quot;), &quot;MCO&quot;, NULL) &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Provider; &quot;), &quot;Provider&quot;, NULL) &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Provider Representative; &quot;), &quot;Provider Representative&quot;, NULL) &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Health Plan; &quot;), &quot;Health Plan&quot;, NULL) &amp;
IF(INCLUDES( Account.Send_Billing_To__c , &quot;Representative&quot;), &quot;Representative&quot;, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Send Billing To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/CaseEntityJunction__c.object-meta.xml
<CustomObject>
    <label>Participant Entity</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Entity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseEntityJunction__c/fields/Addressee__c.field-meta.xml
<CustomField>
    <fullName>Addressee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Addressee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Entity</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Entity_Contact__r.Contact_Person_First_Name__c &amp; &quot; &quot; &amp; Entity_Contact__r.Contact_Person_Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Created_By_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>Created_By_MDIRO__c</fullName>
    <label>Created By</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Participant Entities</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity_Address__c.Entity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Entity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Address_f__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address_f__c</fullName>
    <formula>Entity_Address__r.Address_1__c &amp; &quot; &quot; &amp; BR()  
&amp; Entity_Address__r.Address_2__c  &amp; &quot; &quot; &amp;  BR() &amp; Entity_Address__r.City__c  &amp; &quot;, &quot; 
&amp; TEXT(Entity_Address__r.State__c)  &amp; &quot; &quot; &amp;  Entity_Address__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entity Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Entity_Contact__c.Entity_Address__c</field>
            <operation>equals</operation>
            <valueField>$Source.Entity_Address__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Participant Entities</relationshipLabel>
    <relationshipName>Entiy_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <formula>Entity__r.Primary_Name__c &amp; &quot; &quot; &amp;  Entity__r.Secondary_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Is_Send_Billing_To__c.field-meta.xml
<CustomField>
    <fullName>Is_Send_Billing_To__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Billing To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CaseEntityJunction__c/fields/Send_Billing_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Billing_To__c</fullName>
    <formula>IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Client&quot;)  &amp;&amp;  Entity_Type__c = &quot;Client&quot;, true, false) ||
IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Health Plan&quot;) &amp;&amp; Entity_Type__c = &quot;Health Plan&quot;, true, false) ||
IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Law Firm&quot;) &amp;&amp; Entity_Type__c = &quot;Law Firm&quot;, true, false) ||
IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;MCO&quot;) &amp;&amp; Entity_Type__c = &quot;MCO&quot;, true, false) ||
IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Provider&quot;) &amp;&amp; Entity_Type__c = &quot;Provider&quot;, true, false) ||
IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Provider Representative&quot;) &amp;&amp; Entity_Type__c = &quot;Provider Representative&quot;, true, false) ||
IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Representative&quot;) &amp;&amp; Entity_Type__c = &quot;Health Plan&quot;, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Send Billing To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <inlineHelpText>Only for MDIRO MCOs</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/Entity_Address__c.object-meta.xml
<CustomObject>
    <label>Entity Address</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Address__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entity_Address__c/fields/Entity_Contact__c.field-meta.xml
<CustomField>
    <fullName>Entity_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Contact</label>
    <referenceTo>Entity_Contact__c</referenceTo>
    <relationshipLabel>Entity Addresses</relationshipLabel>
    <relationshipName>Entity_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/Entity_Contact__c.object-meta.xml
<CustomObject>
    <label>Entity Contact</label>
    <nameField>
        <label>Contact Person First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity_Contact__c/fields/Contact_Person_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_First_Name__c</fullName>
    <label>Contact Person First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Contact_Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person_Last_Name__c</fullName>
    <label>Contact Person Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Created_By_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>Created_By_MDIRO__c</fullName>
    <label>Created By</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity_Contact__c/fields/Entity_Address__c.field-meta.xml
<CustomField>
    <fullName>Entity_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Address</label>
    <referenceTo>Entity_Address__c</referenceTo>
    <relationshipLabel>Entity Contacts</relationshipLabel>
    <relationshipName>Entity_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participants Enrollee</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants - Enrollee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Addressee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Individual</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Created_By_MDIRO__c.field-meta.xml
<CustomField>
    <fullName>Created_By_MDIRO__c</fullName>
    <label>Created By</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipName>Participants_Enrollee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Send_Billing_To__c.field-meta.xml
<CustomField>
    <fullName>Send_Billing_To__c</fullName>
    <formula>IF(INCLUDES( Case__r.Account.Send_Billing_To__c , &quot;Enrollee&quot;), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Send Billing To</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseEntityJunctionTriggerHandler.cls
public with sharing class CaseEntityJunctionTriggerHandler {
    public static void checkAddressee(List<CaseEntityJunction__c> partEnrollee){ 
        
        Set<Id> allEnrolleCaseIds = new Set<Id>();       
        for (CaseEntityJunction__c allEnrolleeCase : partEnrollee) {
            system.debug ('Address__c'+allEnrolleeCase.Addressee__c);
            if (allEnrolleeCase.Addressee__c) {
                allEnrolleCaseIds.add(allEnrolleeCase.Case__c);
            }
        }
        system.debug('CaseIds'+ allEnrolleCaseIds);       
        List<CaseEntityJunction__c> entitList = [Select Id, Addressee__c, Case__c From CaseEntityJunction__c where Addressee__c = true and Case__c IN :allEnrolleCaseIds];           
        List<Participant__c> enroleeList = [Select Id, Address__c, Case__c From Participant__c where Address__c = true and Case__c IN :allEnrolleCaseIds];  

        system.debug('Size'+ entitList.size());
        system.debug('Size'+ enroleeList.size());

        for (CaseEntityJunction__c allEnrollee : partEnrollee) {
            if (allEnrollee.Addressee__c) {
                if (entitList.size() > 0) {
                    allEnrollee.addError ('Another Entity has been selected as Addressee. Please unselect it before selecting this record.');
                }            
                else if (enroleeList.size() > 0) {
                    allEnrollee.addError ('Another Enrollee has been selected as Addressee. Please unselect it before selecting this record.');
                }
            }
        }

    }

    public static void addSendBillingTo(List<CaseEntityJunction__c> partEntity){
        for (CaseEntityJunction__c allpartEntity : partEntity) {
                allpartEntity.Is_Send_Billing_To__c = allpartEntity.Send_Billing_To__c;
        }
    }

    public static void updatecaseaddressee(List<CaseEntityJunction__c> CaseEntity){ 
        try {
            String Address1;
            for (CaseEntityJunction__c co : CaseEntity){
                Case po = [SELECT Id, Document_Address__c,Document_Addressee__c  FROM Case WHERE Id = :co.Case__c];
                
                List<CaseEntityJunction__c> l_co = [SELECT Id,Contact_Name__c,Entity__c,Entity_Name__c,Addressee__c,Entity_Address_f__c,Entity_Address__r.Address_1__c, 
                Entity_Address__r.Address_2__c,Entity_Address__r.City__c,Entity_Address__r.State__c,Entity_Address__r.Zip__c FROM CaseEntityJunction__c WHERE Case__c = :po.Id AND Addressee__c = true];
                for(CaseEntityJunction__c am_co : l_co) {
                    if (l_co[0].Entity_Address__r.Address_2__c != null) 
                        Address1 = l_co[0].Contact_Name__c + '\n' + l_co[0].Entity_Address__r.Address_1__c + '\n' + l_co[0].Entity_Address__r.Address_2__c + '\n' + l_co[0].Entity_Address__r.City__c + ', ' + l_co[0].Entity_Address__r.State__c + ' ' + l_co[0].Entity_Address__r.Zip__c;                        
                    else                        
                        Address1 = l_co[0].Contact_Name__c + '\n' + l_co[0].Entity_Address__r.Address_1__c + '\n' + l_co[0].Entity_Address__r.City__c + ', ' + l_co[0].Entity_Address__r.State__c + ' ' + l_co[0].Entity_Address__r.Zip__c;                        
                }               
                po.Document_Address__c = Address1;
                po.Document_Addressee__c = l_co[0].Contact_Name__c;
                update po;
            }
        } catch (Exception e) {
            System.debug(e);
        }
    }
    
    public static void MDIROCaseSubmissionNotification(List<CaseEntityJunction__c> CaseEntity){
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        for(CaseEntityJunction__c cEn: [select Id,Case__r.Program_Code__c,Entity_Contact__r.Email_Address__c,Case__r.Created_By_MDIRO__c,
                                       Entity_Contact__r.Contact_Person_First_Name__c,Entity_Contact__r.Contact_Person_Last_Name__c,Entity_Contact__r.Suffix__c,
                                       Case__r.Received_Date__c,Case__r.Document_Case_Number__c,Case__r.Case_Number_f__c from CaseEntityJunction__c where Id IN : CaseEntity ]){
            if(cEn.Case__r.Program_Code__c == 'IR' && cEn.Entity_Contact__r.Email_Address__c == cEn.Case__r.Created_By_MDIRO__c){
               String converted = cEn.Case__r.Received_Date__c.format('MM/dd/yyyy HH:mm a', 'America/New_York');
                system.debug('===== converted ==== '+converted);
                String suffix;
                if(cEn.Entity_Contact__r.Suffix__c != null){
                    suffix = cEn.Entity_Contact__r.Suffix__c;
                }else{
                    suffix = '';
                }
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                List<String> toAddress = new List<String> ();
                toAddress.add(cEn.Entity_Contact__r.Email_Address__c);
                message.setToAddresses(toAddress);
                String body = '<html>Dear '+cEn.Entity_Contact__r.Contact_Person_First_Name__c+' '+cEn.Entity_Contact__r.Contact_Person_Last_Name__c+' '+suffix+','+
                    '<br/>'+
                    '<br/>'+
                    'Thank you for submitting your case for review on the MD IRO Portal. We received your request on '+converted+' ET and created case number '+cEn.Case__r.Document_Case_Number__c+' per your submission.'+
                    '<br/>'+
                    '<br/>'+
                    'You may view the status of this case at any time, by logging into your portal account.'+
                    '<br/>'+
                    '<br/>'+
                    'Please <a href = "https://mdiro.maximus.com">click here</a> to access the MD IRO Portal.'+
                    '<br/>'+
                    '<br/>'+
                    '<b>Note: Maximus will notify you if there was an issue with your document(s) submission in a separate email.</b>'+
                    '<br/>'+
                    '<br/>'+
                    'Thank you,'+
                    '<br/>'+
                    'MD IRO Staff'+
                    '<br/>'+
                    'MAXIMUS Federal Services</html>';
                message.setHtmlBody(body);
                message.setSubject('Request for Case Review – Submission Confirmation');
                mails.add(message);
            }
        }
        Messaging.SendEmailResult[] result = Messaging.sendEmail(mails);
        System.debug('result0'+result);
    }
}